"""add categories

Revision ID: 20260123_add_categories
Revises: c09bd9294696
Create Date: 2026-01-23 18:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20260123_add_categories'
down_revision: Union[str, None] = 'c09bd9294696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if tables exist before creating
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Categories table
    if 'categories' not in existing_tables:
        op.create_table(
            'categories',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False, unique=True),
            sa.Column('slug', sa.String(length=100), nullable=False, unique=True),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('icon', sa.String(length=50), nullable=True),
            sa.Column('color', sa.String(length=7), nullable=True, server_default='#0d9488'),
            sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'),
            sa.Column('parent_id', postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column('order', sa.Integer(), nullable=False, server_default='0'),
            sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
            sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
            sa.PrimaryKeyConstraint('id')
        )
        
        # Create indexes only if table was created
        op.create_index(op.f('ix_categories_slug'), 'categories', ['slug'], unique=True)
        op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
        op.create_index(op.f('ix_categories_parent_id'), 'categories', ['parent_id'], unique=False)
        op.create_index(op.f('ix_categories_is_active'), 'categories', ['is_active'], unique=False)
    
    # Course-Category association table
    if 'course_categories' not in existing_tables:
        op.create_table(
            'course_categories',
            sa.Column('course_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('category_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('course_id', 'category_id')
        )
        op.create_index(op.f('ix_course_categories_course_id'), 'course_categories', ['course_id'], unique=False)
        op.create_index(op.f('ix_course_categories_category_id'), 'course_categories', ['category_id'], unique=False)
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_categories_category_id'), table_name='course_categories')
    op.drop_index(op.f('ix_course_categories_course_id'), table_name='course_categories')
    op.drop_table('course_categories')
    op.drop_index(op.f('ix_categories_is_active'), table_name='categories')
    op.drop_index(op.f('ix_categories_parent_id'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_slug'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
