"""epic10_extend_lesson_types

Revision ID: 44867ed6fbe5
Revises: 20260212_epic9
Create Date: 2026-02-09 03:30:40.454370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44867ed6fbe5'
down_revision: Union[str, None] = '20260212_epic9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # EPIC-10: LessonType enum'una yeni değerler ekle (idempotent)
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'document' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'lessontype')) THEN
                ALTER TYPE lessontype ADD VALUE 'document';
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'presentation' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'lessontype')) THEN
                ALTER TYPE lessontype ADD VALUE 'presentation';
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'live_lesson' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'lessontype')) THEN
                ALTER TYPE lessontype ADD VALUE 'live_lesson';
            END IF;
        END $$;
    """)
    op.execute("""
        DO $$ 
        BEGIN
            IF NOT EXISTS (SELECT 1 FROM pg_enum WHERE enumlabel = 'text' AND enumtypid = (SELECT oid FROM pg_type WHERE typname = 'lessontype')) THEN
                ALTER TYPE lessontype ADD VALUE 'text';
            END IF;
        END $$;
    """)
    
    # ========================================================================
    # BÖLÜM 2: Lessons Tablosu Kolon Ekleme (EP10-BE-03)
    # ========================================================================
    # EPIC-10: lessons tablosuna yeni kolonlar ekle
    op.add_column('lessons', sa.Column('content_text', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('original_filename', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('file_size_bytes', sa.Integer(), nullable=True))
    op.add_column('lessons', sa.Column('mime_type', sa.String(length=100), nullable=True))
    op.add_column('lessons', sa.Column('thumbnail_path', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('live_lesson_url', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('live_lesson_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('lessons', sa.Column('live_lesson_recording_path', sa.String(length=500), nullable=True))
    op.add_column('lessons', sa.Column('is_live_lesson_ended', sa.Boolean(), nullable=False, server_default='false'))
    
    # ========================================================================
    # BÖLÜM 3: Data Integrity Constraints (EP10-BE-03)
    # ========================================================================
    # Data integrity: file_size_bytes >= 0 constraint
    op.create_check_constraint(
        'ck_lessons_file_size_bytes_non_negative',
        'lessons',
        sa.text('file_size_bytes IS NULL OR file_size_bytes >= 0')
    )
    
    # ========================================================================
    # BÖLÜM 4: Index'ler (EP10-BE-03, EP10-BE-06)
    # ========================================================================
    # lesson_type index (tip bazlı sorgular için)
    op.create_index(op.f('ix_lessons_lesson_type'), 'lessons', ['lesson_type'], unique=False)
    
    # live_lesson_at index (canlı ders sorguları için performans)
    # Index'i sadece bir kez oluştur (duplicate hatası önleme)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if inspector.has_table('lessons'):
        indexes = [idx['name'] for idx in inspector.get_indexes('lessons')]
        if 'idx_lessons_live_lesson_at' not in indexes:
            op.create_index('idx_lessons_live_lesson_at', 'lessons', ['live_lesson_at'], unique=False)
    
    # ========================================================================
    # BÖLÜM 5: Diğer Migration'lar (EPIC-9, vb.)
    # ========================================================================
    op.drop_constraint(op.f('fk_course_reviews_approved_by_admin'), 'course_reviews', type_='foreignkey')
    op.create_foreign_key(None, 'course_reviews', 'users', ['approved_by_admin_id'], ['id'])
    op.drop_column('courses', 'category_id')
    
    # NOT: idx_lessons_live_lesson_at index'i yukarıda zaten oluşturuldu, tekrar oluşturma
    op.drop_constraint(op.f('uq_notification_preferences_user_id'), 'notification_preferences', type_='unique')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.drop_constraint(op.f('notification_preferences_user_id_fkey'), 'notification_preferences', type_='foreignkey')
    op.create_foreign_key(None, 'notification_preferences', 'users', ['user_id'], ['id'])
    op.drop_constraint(op.f('notifications_sender_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notifications', 'users', ['sender_id'], ['id'])
    op.alter_column('users', 'expertise_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('users', 'social_links',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'social_links',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('users', 'expertise_tags',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('notifications_sender_id_fkey'), 'notifications', 'users', ['sender_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'notification_preferences', type_='foreignkey')
    op.create_foreign_key(op.f('notification_preferences_user_id_fkey'), 'notification_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_notification_preferences_user_id'), 'notification_preferences', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_lessons_live_lesson_at', table_name='lessons')
    op.drop_index(op.f('ix_lessons_lesson_type'), table_name='lessons')
    
    # Drop constraint before dropping column
    op.drop_constraint('ck_lessons_file_size_bytes_non_negative', 'lessons', type_='check')
    
    op.drop_column('lessons', 'is_live_lesson_ended')
    op.drop_column('lessons', 'live_lesson_recording_path')
    op.drop_column('lessons', 'live_lesson_at')
    op.drop_column('lessons', 'live_lesson_url')
    op.drop_column('lessons', 'thumbnail_path')
    op.drop_column('lessons', 'mime_type')
    op.drop_column('lessons', 'file_size_bytes')
    op.drop_column('lessons', 'original_filename')
    op.drop_column('lessons', 'content_text')
    op.add_column('courses', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'course_reviews', type_='foreignkey')
    op.create_foreign_key(op.f('fk_course_reviews_approved_by_admin'), 'course_reviews', 'users', ['approved_by_admin_id'], ['id'], ondelete='SET NULL')
    
    # Note: PostgreSQL enum'dan değer kaldırma teknik olarak sınırlı
    # Enum değerleri (document, presentation, live_lesson, text) kaldırılmaz,
    # sadece kullanılmaz hale gelir. Mevcut veriler varsa migration başarısız olabilir.
    # ### end Alembic commands ###
