"""Add messaging tables (conversations, messages, user_blocks, message_reports)

Revision ID: 8961b0816dfb
Revises: 20260219_ads_notif
Create Date: 2026-02-23 02:00:21.073565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8961b0816dfb'
down_revision: Union[str, None] = '20260219_ads_notif'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before creating (idempotent migration)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # user_blocks table
    if 'user_blocks' not in existing_tables:
        op.create_table('user_blocks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('blocker_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('blocked_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blocker_id != blocked_id', name='ck_block_different_users'),
    sa.ForeignKeyConstraint(['blocked_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['blocker_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blocker_id', 'blocked_id', name='uq_user_block')
        )
        op.create_index('idx_user_block_blocked', 'user_blocks', ['blocked_id'], unique=False)
        op.create_index('idx_user_block_blocker', 'user_blocks', ['blocker_id'], unique=False)
        op.create_index(op.f('ix_user_blocks_blocked_id'), 'user_blocks', ['blocked_id'], unique=False)
        op.create_index(op.f('ix_user_blocks_blocker_id'), 'user_blocks', ['blocker_id'], unique=False)
    
    # conversations table
    if 'conversations' not in existing_tables:
        op.create_table('conversations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('participant1_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('participant2_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('participant1_role', sa.String(length=20), nullable=False),
    sa.Column('participant2_role', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('conversation_type', sa.String(length=30), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_preview', sa.Text(), nullable=True),
    sa.Column('last_read_at_participant1', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_read_at_participant2', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unread_count_participant1', sa.Integer(), nullable=False),
    sa.Column('unread_count_participant2', sa.Integer(), nullable=False),
    sa.Column('is_archived_participant1', sa.Boolean(), nullable=False),
    sa.Column('is_archived_participant2', sa.Boolean(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('participant1_id != participant2_id', name='ck_different_participants'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['participant1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['participant2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('participant1_id', 'participant2_id', 'course_id', name='uq_conversation_participants')
    )
        op.create_index('idx_conversation_last_message', 'conversations', ['last_message_at'], unique=False)
        op.create_index('idx_conversation_participant1', 'conversations', ['participant1_id'], unique=False)
        op.create_index('idx_conversation_participant2', 'conversations', ['participant2_id'], unique=False)
        op.create_index('idx_conversation_type', 'conversations', ['conversation_type'], unique=False)
        op.create_index(op.f('ix_conversations_course_id'), 'conversations', ['course_id'], unique=False)
        op.create_index(op.f('ix_conversations_participant1_id'), 'conversations', ['participant1_id'], unique=False)
        op.create_index(op.f('ix_conversations_participant2_id'), 'conversations', ['participant2_id'], unique=False)
    
    # messages table
    if 'messages' not in existing_tables:
        op.create_table('messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sender_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('sender_role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('attachment_filename', sa.String(length=255), nullable=True),
    sa.Column('attachment_size', sa.BigInteger(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('flag_reason', sa.String(length=255), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderated_by_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['moderated_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        op.create_index('idx_message_conversation', 'messages', ['conversation_id'], unique=False)
        op.create_index('idx_message_created', 'messages', ['created_at'], unique=False)
        op.create_index('idx_message_flagged', 'messages', ['is_flagged'], unique=False)
        op.create_index('idx_message_sender', 'messages', ['sender_id'], unique=False)
        op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
        op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    
    # message_reports table
    if 'message_reports' not in existing_tables:
        op.create_table('message_reports',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('message_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reporter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'reporter_id', name='uq_message_report')
    )
        op.create_index('idx_message_report_message', 'message_reports', ['message_id'], unique=False)
        op.create_index('idx_message_report_reporter', 'message_reports', ['reporter_id'], unique=False)
        op.create_index(op.f('ix_message_reports_message_id'), 'message_reports', ['message_id'], unique=False)
        op.create_index(op.f('ix_message_reports_reporter_id'), 'message_reports', ['reporter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_reports_reporter_id'), table_name='message_reports')
    op.drop_index(op.f('ix_message_reports_message_id'), table_name='message_reports')
    op.drop_index('idx_message_report_reporter', table_name='message_reports')
    op.drop_index('idx_message_report_message', table_name='message_reports')
    op.drop_table('message_reports')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('idx_message_sender', table_name='messages')
    op.drop_index('idx_message_flagged', table_name='messages')
    op.drop_index('idx_message_created', table_name='messages')
    op.drop_index('idx_message_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_participant2_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_participant1_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_course_id'), table_name='conversations')
    op.drop_index('idx_conversation_type', table_name='conversations')
    op.drop_index('idx_conversation_participant2', table_name='conversations')
    op.drop_index('idx_conversation_participant1', table_name='conversations')
    op.drop_index('idx_conversation_last_message', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_user_blocks_blocker_id'), table_name='user_blocks')
    op.drop_index(op.f('ix_user_blocks_blocked_id'), table_name='user_blocks')
    op.drop_index('idx_user_block_blocker', table_name='user_blocks')
    op.drop_index('idx_user_block_blocked', table_name='user_blocks')
    op.drop_table('user_blocks')
    # ### end Alembic commands ###
