"""Add certificate and certificate_template tables

Revision ID: a23dd055a1e0
Revises: 20260213_epic10_quota_audit
Create Date: 2026-02-11 06:13:42.199278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a23dd055a1e0'
down_revision: Union[str, None] = '20260213_epic10_quota_audit'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_created'), table_name='content_audit_logs')
    op.drop_index(op.f('idx_audit_resource'), table_name='content_audit_logs')
    op.drop_index(op.f('idx_audit_user_action'), table_name='content_audit_logs')
    op.drop_index(op.f('ix_content_audit_logs_action'), table_name='content_audit_logs')
    op.drop_index(op.f('ix_content_audit_logs_created_at'), table_name='content_audit_logs')
    op.drop_index(op.f('ix_content_audit_logs_resource_id'), table_name='content_audit_logs')
    op.drop_index(op.f('ix_content_audit_logs_resource_type'), table_name='content_audit_logs')
    op.drop_index(op.f('ix_content_audit_logs_user_id'), table_name='content_audit_logs')
    op.drop_table('content_audit_logs')
    op.drop_index(op.f('ix_storage_quotas_user_id'), table_name='storage_quotas')
    op.drop_table('storage_quotas')
    op.drop_index(op.f('idx_lessons_live_lesson_at'), table_name='lessons')
    op.alter_column('quiz_attempts', 'started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('quiz_attempts', 'completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_attempts', 'completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('quiz_attempts', 'started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_lessons_live_lesson_at'), 'lessons', ['live_lesson_at'], unique=False)
    op.create_table('storage_quotas',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quota_bytes', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.Column('used_bytes', sa.BIGINT(), server_default=sa.text("'0'::bigint"), autoincrement=False, nullable=False),
    sa.Column('reset_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('reset_period_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_custom', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('storage_quotas_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('storage_quotas_pkey'))
    )
    op.create_index(op.f('ix_storage_quotas_user_id'), 'storage_quotas', ['user_id'], unique=True)
    op.create_table('content_audit_logs',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('content_audit_logs_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('content_audit_logs_pkey'))
    )
    op.create_index(op.f('ix_content_audit_logs_user_id'), 'content_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_content_audit_logs_resource_type'), 'content_audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_content_audit_logs_resource_id'), 'content_audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_content_audit_logs_created_at'), 'content_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_content_audit_logs_action'), 'content_audit_logs', ['action'], unique=False)
    op.create_index(op.f('idx_audit_user_action'), 'content_audit_logs', ['user_id', 'action'], unique=False)
    op.create_index(op.f('idx_audit_resource'), 'content_audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('idx_audit_created'), 'content_audit_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###
